//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisBodyManager.Server.Tests.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.usergroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.group))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.user))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.usergroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.group))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.user))]
    public partial class EntityObject : HisBodyManager.Server.Tests.ServiceReference1.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usergroup", Namespace="http://schemas.datacontract.org/2004/07/HisBodyManager.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class usergroup : HisBodyManager.Server.Tests.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GroupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.group groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfgroupNbXIYouE groupReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfuserNbXIYouE userReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Groupid {
            get {
                return this.GroupidField;
            }
            set {
                if ((this.GroupidField.Equals(value) != true)) {
                    this.GroupidField = value;
                    this.RaisePropertyChanged("Groupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.group group {
            get {
                return this.groupField;
            }
            set {
                if ((object.ReferenceEquals(this.groupField, value) != true)) {
                    this.groupField = value;
                    this.RaisePropertyChanged("group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfgroupNbXIYouE groupReference {
            get {
                return this.groupReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.groupReferenceField, value) != true)) {
                    this.groupReferenceField = value;
                    this.RaisePropertyChanged("groupReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfuserNbXIYouE userReference {
            get {
                return this.userReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.userReferenceField, value) != true)) {
                    this.userReferenceField = value;
                    this.RaisePropertyChanged("userReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="group", Namespace="http://schemas.datacontract.org/2004/07/HisBodyManager.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class group : HisBodyManager.Server.Tests.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.usergroup[] usergroupsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.usergroup[] usergroups {
            get {
                return this.usergroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.usergroupsField, value) != true)) {
                    this.usergroupsField = value;
                    this.RaisePropertyChanged("usergroups");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/HisBodyManager.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class user : HisBodyManager.Server.Tests.ServiceReference1.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChurchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLogInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.usergroup[] usergroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChurchId {
            get {
                return this.ChurchIdField;
            }
            set {
                if ((this.ChurchIdField.Equals(value) != true)) {
                    this.ChurchIdField = value;
                    this.RaisePropertyChanged("ChurchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLogInDate {
            get {
                return this.LastLogInDateField;
            }
            set {
                if ((this.LastLogInDateField.Equals(value) != true)) {
                    this.LastLogInDateField = value;
                    this.RaisePropertyChanged("LastLogInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.usergroup[] usergroups {
            get {
                return this.usergroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.usergroupsField, value) != true)) {
                    this.usergroupsField = value;
                    this.RaisePropertyChanged("usergroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfgroupNbXIYouE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfuserNbXIYouE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.user))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.usergroup[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.usergroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.group))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.user[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.group[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfgroupNbXIYouE", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfgroupNbXIYouE : HisBodyManager.Server.Tests.ServiceReference1.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfuserNbXIYouE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfgroupNbXIYouE))]
    public partial class EntityReference : HisBodyManager.Server.Tests.ServiceReference1.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Server.Tests.ServiceReference1.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Server.Tests.ServiceReference1.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfuserNbXIYouE))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(HisBodyManager.Server.Tests.ServiceReference1.EntityReferenceOfgroupNbXIYouE))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfuserNbXIYouE", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfuserNbXIYouE : HisBodyManager.Server.Tests.ServiceReference1.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IUserManagementService")]
    public interface IUserManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/SaveUser", ReplyAction="http://tempuri.org/IUserManagementService/SaveUserResponse")]
        HisBodyManager.Server.Tests.ServiceReference1.user SaveUser(HisBodyManager.Server.Tests.ServiceReference1.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetAllUsers", ReplyAction="http://tempuri.org/IUserManagementService/GetAllUsersResponse")]
        HisBodyManager.Server.Tests.ServiceReference1.user[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetUser", ReplyAction="http://tempuri.org/IUserManagementService/GetUserResponse")]
        HisBodyManager.Server.Tests.ServiceReference1.user GetUser(HisBodyManager.Server.Tests.ServiceReference1.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/Savegroup", ReplyAction="http://tempuri.org/IUserManagementService/SavegroupResponse")]
        HisBodyManager.Server.Tests.ServiceReference1.group Savegroup(HisBodyManager.Server.Tests.ServiceReference1.group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetGroups", ReplyAction="http://tempuri.org/IUserManagementService/GetGroupsResponse")]
        HisBodyManager.Server.Tests.ServiceReference1.group[] GetGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetGroup", ReplyAction="http://tempuri.org/IUserManagementService/GetGroupResponse")]
        HisBodyManager.Server.Tests.ServiceReference1.group GetGroup(HisBodyManager.Server.Tests.ServiceReference1.group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/SaveUserGroup", ReplyAction="http://tempuri.org/IUserManagementService/SaveUserGroupResponse")]
        HisBodyManager.Server.Tests.ServiceReference1.usergroup SaveUserGroup(HisBodyManager.Server.Tests.ServiceReference1.usergroup userGroup);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementServiceChannel : HisBodyManager.Server.Tests.ServiceReference1.IUserManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementServiceClient : System.ServiceModel.ClientBase<HisBodyManager.Server.Tests.ServiceReference1.IUserManagementService>, HisBodyManager.Server.Tests.ServiceReference1.IUserManagementService {
        
        public UserManagementServiceClient() {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HisBodyManager.Server.Tests.ServiceReference1.user SaveUser(HisBodyManager.Server.Tests.ServiceReference1.user user) {
            return base.Channel.SaveUser(user);
        }
        
        public HisBodyManager.Server.Tests.ServiceReference1.user[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public HisBodyManager.Server.Tests.ServiceReference1.user GetUser(HisBodyManager.Server.Tests.ServiceReference1.user user) {
            return base.Channel.GetUser(user);
        }
        
        public HisBodyManager.Server.Tests.ServiceReference1.group Savegroup(HisBodyManager.Server.Tests.ServiceReference1.group group) {
            return base.Channel.Savegroup(group);
        }
        
        public HisBodyManager.Server.Tests.ServiceReference1.group[] GetGroups() {
            return base.Channel.GetGroups();
        }
        
        public HisBodyManager.Server.Tests.ServiceReference1.group GetGroup(HisBodyManager.Server.Tests.ServiceReference1.group group) {
            return base.Channel.GetGroup(group);
        }
        
        public HisBodyManager.Server.Tests.ServiceReference1.usergroup SaveUserGroup(HisBodyManager.Server.Tests.ServiceReference1.usergroup userGroup) {
            return base.Channel.SaveUserGroup(userGroup);
        }
    }
}
