//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisBodyManager.Web.UI.UserManagementServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="user", Namespace="http://schemas.datacontract.org/2004/07/HisBodyManager.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class user : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChurchIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastLogInDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Web.UI.UserManagementServiceReference.usergroup[] usergroupsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChurchId {
            get {
                return this.ChurchIdField;
            }
            set {
                if ((this.ChurchIdField.Equals(value) != true)) {
                    this.ChurchIdField = value;
                    this.RaisePropertyChanged("ChurchId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastLogInDate {
            get {
                return this.LastLogInDateField;
            }
            set {
                if ((this.LastLogInDateField.Equals(value) != true)) {
                    this.LastLogInDateField = value;
                    this.RaisePropertyChanged("LastLogInDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Web.UI.UserManagementServiceReference.usergroup[] usergroups {
            get {
                return this.usergroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.usergroupsField, value) != true)) {
                    this.usergroupsField = value;
                    this.RaisePropertyChanged("usergroups");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="usergroup", Namespace="http://schemas.datacontract.org/2004/07/HisBodyManager.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class usergroup : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GroupidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> UserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Web.UI.UserManagementServiceReference.group groupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<HisBodyManager.Web.UI.UserManagementServiceReference.group> groupReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Web.UI.UserManagementServiceReference.user userField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.Objects.DataClasses.EntityReference<HisBodyManager.Web.UI.UserManagementServiceReference.user> userReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Groupid {
            get {
                return this.GroupidField;
            }
            set {
                if ((this.GroupidField.Equals(value) != true)) {
                    this.GroupidField = value;
                    this.RaisePropertyChanged("Groupid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((this.UserIdField.Equals(value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Web.UI.UserManagementServiceReference.group group {
            get {
                return this.groupField;
            }
            set {
                if ((object.ReferenceEquals(this.groupField, value) != true)) {
                    this.groupField = value;
                    this.RaisePropertyChanged("group");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<HisBodyManager.Web.UI.UserManagementServiceReference.group> groupReference {
            get {
                return this.groupReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.groupReferenceField, value) != true)) {
                    this.groupReferenceField = value;
                    this.RaisePropertyChanged("groupReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Web.UI.UserManagementServiceReference.user user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.Objects.DataClasses.EntityReference<HisBodyManager.Web.UI.UserManagementServiceReference.user> userReference {
            get {
                return this.userReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.userReferenceField, value) != true)) {
                    this.userReferenceField = value;
                    this.RaisePropertyChanged("userReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="group", Namespace="http://schemas.datacontract.org/2004/07/HisBodyManager.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class group : System.Data.Objects.DataClasses.EntityObject, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsActiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HisBodyManager.Web.UI.UserManagementServiceReference.usergroup[] usergroupsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive {
            get {
                return this.IsActiveField;
            }
            set {
                if ((this.IsActiveField.Equals(value) != true)) {
                    this.IsActiveField = value;
                    this.RaisePropertyChanged("IsActive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HisBodyManager.Web.UI.UserManagementServiceReference.usergroup[] usergroups {
            get {
                return this.usergroupsField;
            }
            set {
                if ((object.ReferenceEquals(this.usergroupsField, value) != true)) {
                    this.usergroupsField = value;
                    this.RaisePropertyChanged("usergroups");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserManagementServiceReference.IUserManagementService")]
    public interface IUserManagementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/SaveUser", ReplyAction="http://tempuri.org/IUserManagementService/SaveUserResponse")]
        HisBodyManager.Web.UI.UserManagementServiceReference.user SaveUser(HisBodyManager.Web.UI.UserManagementServiceReference.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetAllUsers", ReplyAction="http://tempuri.org/IUserManagementService/GetAllUsersResponse")]
        HisBodyManager.Web.UI.UserManagementServiceReference.user[] GetAllUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetUser", ReplyAction="http://tempuri.org/IUserManagementService/GetUserResponse")]
        HisBodyManager.Web.UI.UserManagementServiceReference.user GetUser(HisBodyManager.Web.UI.UserManagementServiceReference.user user);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/Savegroup", ReplyAction="http://tempuri.org/IUserManagementService/SavegroupResponse")]
        HisBodyManager.Web.UI.UserManagementServiceReference.group Savegroup(HisBodyManager.Web.UI.UserManagementServiceReference.group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetGroups", ReplyAction="http://tempuri.org/IUserManagementService/GetGroupsResponse")]
        HisBodyManager.Web.UI.UserManagementServiceReference.group[] GetGroups();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/GetGroup", ReplyAction="http://tempuri.org/IUserManagementService/GetGroupResponse")]
        HisBodyManager.Web.UI.UserManagementServiceReference.group GetGroup(HisBodyManager.Web.UI.UserManagementServiceReference.group group);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserManagementService/SaveUserGroup", ReplyAction="http://tempuri.org/IUserManagementService/SaveUserGroupResponse")]
        HisBodyManager.Web.UI.UserManagementServiceReference.usergroup SaveUserGroup(HisBodyManager.Web.UI.UserManagementServiceReference.usergroup userGroup);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserManagementServiceChannel : HisBodyManager.Web.UI.UserManagementServiceReference.IUserManagementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserManagementServiceClient : System.ServiceModel.ClientBase<HisBodyManager.Web.UI.UserManagementServiceReference.IUserManagementService>, HisBodyManager.Web.UI.UserManagementServiceReference.IUserManagementService {
        
        public UserManagementServiceClient() {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserManagementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HisBodyManager.Web.UI.UserManagementServiceReference.user SaveUser(HisBodyManager.Web.UI.UserManagementServiceReference.user user) {
            return base.Channel.SaveUser(user);
        }
        
        public HisBodyManager.Web.UI.UserManagementServiceReference.user[] GetAllUsers() {
            return base.Channel.GetAllUsers();
        }
        
        public HisBodyManager.Web.UI.UserManagementServiceReference.user GetUser(HisBodyManager.Web.UI.UserManagementServiceReference.user user) {
            return base.Channel.GetUser(user);
        }
        
        public HisBodyManager.Web.UI.UserManagementServiceReference.group Savegroup(HisBodyManager.Web.UI.UserManagementServiceReference.group group) {
            return base.Channel.Savegroup(group);
        }
        
        public HisBodyManager.Web.UI.UserManagementServiceReference.group[] GetGroups() {
            return base.Channel.GetGroups();
        }
        
        public HisBodyManager.Web.UI.UserManagementServiceReference.group GetGroup(HisBodyManager.Web.UI.UserManagementServiceReference.group group) {
            return base.Channel.GetGroup(group);
        }
        
        public HisBodyManager.Web.UI.UserManagementServiceReference.usergroup SaveUserGroup(HisBodyManager.Web.UI.UserManagementServiceReference.usergroup userGroup) {
            return base.Channel.SaveUserGroup(userGroup);
        }
    }
}
